version: '3.7'
services:

  twhui:
    container_name: twhui
    build:
      context: .
      dockerfile: Dockerfile
    #command: 'tail -f /dev/null'
    volumes:
      - './:/home/twhadm'
      - '/home/twhadm/node_modules'
    env_file: .env
    ports:
      - "3000:3000"
